/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCountdown: typeof import('element-plus/es')['ElCountdown']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElResult: typeof import('element-plus/es')['ElResult']
    Exception: typeof import('./components/Exception/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./components/Table/index.vue')['default']
  }
}
